# Generated by Django 5.2.5 on 2025-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('user', 'User')], default='user', max_length=10, verbose_name='role'),
        ),
    ]
